require("settings.options")
require("settings.lazy")
require("settings.lspconfig")
require("settings.treesitter")
require("settings.highlighting")
require("settings.cmp")
vim.cmd("colorscheme kanagawa")
