require("settings.options")
require("settings.lazy")
require("settings.lspconfig")
require("settings.harpoon")
require("settings.treesitter")
require("settings.highlighting")
require("settings.jupynium")
require("settings.cmp")
require("custom.manim")
vim.cmd("colorscheme kanagawa")
vim.keymap.set('n', ',f', "<cmd>Telescope find_files<CR>", { noremap = true, silent = true })
